version: "3.1"
services:
  service_db:
    image: mysql:5.7
    volumes:
      - ./mysql_init/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    ports:
      - "3312:3306"
    environment:
      MYSQL_DATABASE: service_db
      MYSQL_ROOT_USER: udaniklean
      MYSQL_USER: udaniklean
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret

  adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080